[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "tests"
script = "script-backup"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]
